stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw/imdb_train.csv
    - data/raw/imdb_validation.csv
    - data/raw/imdb_test.csv
    
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - src/data_preprocessing.py
    - data/raw/imdb_train.csv
    - data/raw/imdb_validation.csv
    - data/raw/imdb_test.csv
    outs:
    - data/processed/imdb_train.csv
    - data/processed/imdb_validation.csv
    - data/processed/imdb_test.csv

  model_building:
    cmd: python src/model_training.py
    deps:
    - src/model_training.py
    - data/processed/imdb_train.csv
    params:
    - Train.Vectorizer
    - Train.LR
  
    

  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - src/model_evaluation.py
    - models/tfidf_vectorizer.pkl
    - models/logistic_regression_model.pkl
    - data/processed/imdb_train.csv
    - data/processed/imdb_validation.csv
    - data/processed/imdb_test.csv
    


    
  
    